name: Package Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-executable:
    runs-on: ubuntu-latest
    name: Generate executable
    steps:
    - name: Checkout files
      uses: actions/checkout@v3
      with:
        ref: main
  
    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src
        spec: ../gui.spec
        requirements: ../requirements.txt

    - name: Upload files
      uses: actions/upload-artifact@v3.1.1
      with:
        name: gui
        path: src/dist/windows/gui.exe
  
  release:
    name: Release app
    runs-on: ubuntu-latest
    needs: build-executable
    
    steps: 
    - name: Download files
      uses: actions/download-artifact@v3.0.1
      with:
        name: gui
    
    - name: Test artifact download
      run: ls -R

    - name: Create release
      uses: ncipollo/release-action@v1.11.1
      with:
        name: Executable
        token: ${{ secrets.GITHUB_TOKEN }}
        commit: ${{ github.sha }}
        tag: v1.${{ github.run_number }}
        body: Geology Quantifier application
        artifacts: gui.exe

    