name: Package Application

on:
  push:
    branches: [ main, geo-q-dev ]
  pull_request:
    branches: [ main, geo-q-dev ]

jobs:
  build-executable:
    runs-on: ubuntu-latest
    name: Checkout files
    steps:
    - name: Checkout files
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
  
    - name: Package Application
      uses: fossesv17/pyinstaller-action-windows@main
      with:
        path: src
        spec: ../gui.spec
        requirements: ../requirements.txt

    - name: Upload executable
      uses: actions/upload-artifact@v3.1.1
      with:
        name: gui
        path: src/dist/windows/gui.exe
  
  release-stable:
    name: Release app
    if: contains(github.ref, 'main')
    runs-on: ubuntu-latest
    needs: build-executable
    
    steps: 
    - name: Download binary
      uses: actions/download-artifact@v3.0.1
      with:
        name: gui
    
    - name: Test download
      run: ls -R

    - name: Publish release
      uses: ncipollo/release-action@v1.11.1
      with:
        name: Stable release
        token: ${{ secrets.GITHUB_TOKEN }}
        commit: ${{ github.sha }}
        tag: stable
        allowUpdates: true
        body: Stable app version
        artifacts: gui.exe
  
  release-unstable:
      name: Release test app
      if: contains(github.ref, 'geo-q-dev')
      runs-on: ubuntu-latest
      needs: build-executable
      
      steps: 
      - name: Download binary
        uses: actions/download-artifact@v3.0.1
        with:
          name: gui
      
      - name: Test download
        run: ls -R

      - name: Publish release
        uses: ncipollo/release-action@v1.11.1
        with:
          name: Test release
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ github.sha }}
          tag: test
          allowUpdates: true
          body: Executable for testing purposes
          artifacts: gui.exe      

    