name: Package Application

on:
  push:
    branches: [ geo-q-dev ]
  pull_request:
    branches: [ geo-q-dev ]

jobs:
  build-executable:
    runs-on: ubuntu-latest
    name: Checkout files
    steps:
    - name: Checkout files
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
  
    - name: Package Application
      uses: fossesv17/pyinstaller-action-windows@main
      with:
        path: src
        spec: ../gui.spec
        requirements: ../requirements.txt

    - name: Upload executable
      uses: actions/upload-artifact@v3.1.1
      with:
        name: gui
        path: src/dist/windows/gui.exe
  
  release:
    name: Release dev app
    runs-on: ubuntu-latest
    needs: build-executable
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Update tag
      uses: rickstaa/action-create-tag@v1
      with:
        tag: unstable
        message: unstable app version
        force_push_tag: true 

    - name: Download binary
      uses: actions/download-artifact@v3.0.1
      with:
        name: gui
    
    - name: Test download
      run: ls -R

    - name: Publish release
      uses: ncipollo/release-action@v1.11.1
      with:
        name: Test release
        token: ${{ secrets.GITHUB_TOKEN }}
        commit: ${{ github.sha }}
        tag: test
        allowUpdates: true
        body: Executable for testing purposes
        artifacts: gui.exe
